import React,{useEffect,useState}from"react";import{createRoot}from"react-dom/client";import{LayoutDashboard,Code2,Boxes,Network,GitBranch,AlertTriangle,BookOpen,BrainCircuit,Sparkles,CheckCircle2}from"lucide-react";import ReactFlow,{Background,Controls,MiniMap}from"reactflow";import"reactflow/dist/style.css";import"./style.css";
const API="http://localhost:5000/api";const mods=["CUSTOMER","ACCOUNT","TRANSACTION","PAYMENT","DATABASE","AUDIT","REPORT","AUTHENTICATION"];const edges=[["AUTHENTICATION","CUSTOMER"],["CUSTOMER","ACCOUNT"],["ACCOUNT","TRANSACTION"],["TRANSACTION","PAYMENT"],["TRANSACTION","DATABASE"],["PAYMENT","DATABASE"],["PAYMENT","AUDIT"],["DATABASE","REPORT"],["AUDIT","REPORT"]];
function App(){const[p,setP]=useState("Dashboard"),[data,setData]=useState(null),[impact,setImpact]=useState(null),[change,setChange]=useState("Change payment validation rule"),[msg,setMsg]=useState("");
useEffect(()=>{fetch(API+"/system").then(r=>r.json()).then(setData).catch(()=>{})},[]);
const analyze=()=>fetch(API+"/analysis/analyze",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({code:`PROGRAM-ID. PAYMENT.\nPERFORM VALIDATE-PAYMENT\nCALL 'DATABASE'\nCALL 'AUDIT'\nEXEC SQL UPDATE ACCOUNT SET BALANCE = BALANCE - :AMOUNT END-EXEC.`})}).then(r=>r.json()).then(x=>{setData({...data,...x});setMsg("Demo analysis complete");});
const runImpact=()=>fetch(API+"/impact",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({module:"PAYMENT",change})}).then(r=>r.json()).then(x=>{setImpact(x);setP("Impact Analysis")});
const nav=[["Dashboard",LayoutDashboard],["Code Analysis",Code2],["Modules",Boxes],["Dependency Graph",Network],["Digital Twin",GitBranch],["Impact Analysis",AlertTriangle],["Documentation",BookOpen]];
return <div className="app"><aside><div className="brand"><BrainCircuit/> <b>LegacyMind</b></div>{nav.map(([n,I])=><button className={p===n?"active":""} onClick={()=>setP(n)}><I size={18}/>{n}</button>)}<small>Developer Productivity</small></aside><main><header><div><small>LEGACY SYSTEM INTELLIGENCE</small><h1>{p}</h1></div><button className="demo" onClick={analyze}><Sparkles size={17}/>Run Demo</button></header>
{p==="Dashboard"&&<><section className="hero"><span>● ANALYSIS ENGINE ONLINE</span><h2>Understand. Simulate. Change safely.</h2><p>LegacyMind analyzes legacy COBOL systems, maps dependencies and explains change impact.</p><button className="demo" onClick={analyze}>Analyze Sample COBOL →</button></section><div className="grid">{[["Programs",8],["Dependencies",10],["Files",6],["SQL Operations",12]].map(x=><div className="card"><small>{x[0]}</small><strong>{x[1]}</strong></div>)}</div><section className="card"><h3>System Modules</h3><div className="chips">{mods.map(m=><span>{m}</span>)}</div></section></>}
{p==="Code Analysis"&&<section className="card"><h3>COBOL Code Analysis</h3><pre>{`PROGRAM-ID. PAYMENT.\n\nPERFORM VALIDATE-PAYMENT\nCALL 'DATABASE'\nCALL 'AUDIT'\nEXEC SQL\n UPDATE ACCOUNT SET BALANCE = BALANCE - :AMOUNT\nEND-EXEC.`}</pre><button className="demo" onClick={analyze}>Analyze Code</button>{data?.found&&<div className="chips">{data.found.map(x=><span>✓ {x}</span>)}</div>}</section>}
{p==="Modules"&&<section className="card"><h3>Detected Modules</h3>{mods.map((m,i)=><div className="row"><b>{m}</b><span>{i%3===0?"High":i%2?"Medium":"Low"}</span><small>Legacy program / business component</small></div>)}</section>}
{p==="Dependency Graph"&&<Graph/>}
{p==="Digital Twin"&&<section className="card"><h3>Digital Twin</h3><p>Interactive architectural representation of the legacy banking system.</p><Graph/></section>}
{p==="Impact Analysis"&&<section className="card"><h3>Change Impact Analysis</h3><label>Proposed change</label><input value={change} onChange={e=>setChange(e.target.value)}/><button className="demo" onClick={runImpact}>Analyze Impact</button>{impact&&<div className="impact"><h2>Risk: {impact.risk} · Score {impact.score}/100</h2><p>{impact.reason}</p><b>Affected modules</b><div className="chips">{impact.affected.map(x=><span>{x}</span>)}</div><b>Evidence</b><pre>{impact.evidence.join("\n")}</pre></div>}</section>}
{p==="Documentation"&&<section className="card"><h3>Generated Documentation</h3><h4>PAYMENT</h4><p>Handles payment validation, database posting and audit logging.</p><h4>Dependencies</h4><p>PAYMENT → DATABASE → REPORT<br/>PAYMENT → AUDIT → REPORT</p><h4>Change Safety</h4><p>Review downstream persistence and audit behavior before modifying payment logic.</p></section>}
{msg&&<div className="toast"><CheckCircle2 size={16}/>{msg}</div>}</main></div>}
function Graph(){const nodes=mods.map((m,i)=>({id:m,data:{label:m},position:{x:(i%4)*210,y:Math.floor(i/4)*150}}));const es=edges.map((e,i)=>({id:"e"+i,source:e[0],target:e[1],animated:true}));return <div className="graph"><ReactFlow nodes={nodes} edges={es} fitView><MiniMap/><Controls/><Background/></ReactFlow></div>}createRoot(document.getElementById("root")).render(<App/>);